### ISSUE TITLE
Break out requirements into environments

### ISSUE THREAD

**Issue by patrickbeeson** [portlandpython/portlandpython.org#10]
Cherry pick requirements from requirements.txt and put into distinct requirements files for each environment. This will cut down on unneeded items such as django-extensions and iPython which aren't needed in production.

**Comment by hanneshapke** [comment]
Hi Patrick, 

Great suggestion. I had moved the requirements to its own folder and started a test_requirements.txt file.
I can merge the branches so that we have the requirements folder structure.

**Comment by ChrisFreeman** [comment]
Current limiting factor: Requirement `gnureadline` depends on `libncurses5`
Until requirements are sorted, fix is `sudo apt-get install libncurses5-dev`

**Comment by patrickbeeson** [comment]
Requirements have been separated into base and test. Further separation could be done.
