### ISSUE TITLE
Resolve serving of static assets

### ISSUE THREAD

**Issue by patrickbeeson** [portlandpython/portlandpython.org#4]
Includes all static items such as images, css, js, etc.

**Comment by patrickbeeson** [comment]
Here's an idea: https://devcenter.heroku.com/articles/django-assets

**Comment by ChrisFreeman** [comment]
+1 Seems reasonable.

**Comment by patrickbeeson** [comment]
We'll use WhiteNoise to serve static files on Heroku.
