### ISSUE TITLE
Setting up travis CI support

### ISSUE THREAD

**Issue by hanneshapke** [portlandpython/portlandpython.org#6]
Hi all, 

When I spoke with Joe and Bracket last Thursday, they mentioned that a setup of 

```
Push to Github Master > Continuos Integration System > Automatic Deployment to Heroku
```

is envision for the `portlandpython.org` site. I agree with that, since it is a good example for best practice and Django beginners could potentially simply copy our `.travis.yml` settings and run their open source projects with it.

Any objections to setting up a CI system?

There is a large number of hosted CI services available with pros/cons:
- Travis CI (for for open source repos)
- Circle CI (free private repo)
- Codeship (free private repo first 100 builds/months)
- etc.

[Travis CI](https://travis-ci.org/) seems to be the de facto standard for open source CI and therefore I would opt for that. 

Any objections of using Travis CI?

I would be happy to set up the repo test config for python 2.7 and 3.4/5 if everyone is ok with that.

**Comment by patrickbeeson** [comment]
That sounds great!

**Comment by ChrisFreeman** [comment]
Fantastic!

**Comment by patrickbeeson** [comment]
Travis has been integrated on dev and master.
