### ISSUE TITLE
Determine how we should handle email sending

### ISSUE THREAD

**Issue by patrickbeeson** [portlandpython/portlandpython.org#9]
Any thoughts on a service we can use here? I've had success with Sendgrid and Mailgun, the latter of which is free under 10K emails (which we'd likely be under).

Any issues proceeding with Mailgun or is there a better solution?

**Comment by robotbill** [comment]
What do we need to send emails for?

**Comment by patrickbeeson** [comment]
Error emails generally, but this could extend to contact form/signup notifications or anything involving user engagement.

**Comment by patrickbeeson** [comment]
Let's use Mailgun for now. Closing...
